
title: HackyHour @ JCU
description: "Providing digital solutions to JCU research staff & students"

titleBackground: "https://raw.githubusercontent.com/anelda/GenomicsHackyHour/gh-pages/img/technology-785742_1280.jpg"
headlineSmall: "HackyHour @ JCU" # 
headlineMain: "Sharing our digital skills to improve your science" # Need a better tag line

# Setup Google Calendar
# Usage:
# 1. create a new google account; set the calendar to 'public'
# 2. change 'USER' in the example urls below to the username of the google account you made for your calendar
# 3. set calendar_on: True.

calendar_on: True
calendar_embed_url: "https://www.google.com/calendar/embed?src=JCU.HackyHour@gmail.com"
calendar_ical_url: "https://www.google.com/calendar/ical/JCU.HackyHour@gmail.com/public/basic.ics"


#========================================
# No touching anything below this line :)
#========================================
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 248F24
  secondary: CF0000
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
future: True
